app.py
from flask import Flask
from routes import pages, posts, api
from flask_mobility import Mobility

app = Flask(__name__)
app.register_blueprint(pages.pages)
app.register_blueprint(posts.posts)
app.register_blueprint(api.api)
Mobility(app)

if __name__ == '__main__':
    app.run(port=5001)

routes/api.py
from flask import Blueprint, request, Response, render_template
from routes.functions import _get_posts
api = Blueprint('api', __name__)


@api.route('/api')
def api_home():
    posts = _get_posts()
    return render_template('tools.html', **locals())


@api.route('/api/lodge-pingback')
def lodge_pingback():
    uri = request.args.get('uri')
    if uri is not None and uri != '':
        uri_txt = 'for the resource {}.'.format(uri)
    else:
        uri_txt = 'but you forgot to specify the URI you\'re pinging back for!'

    txt = '''Thanks for pinging back {} Unfortunately this site can't yet handle pingbacks. ''' \
          '''Please send Nick and email to let him know what you're doing though as he's be most interested in ''' \
          '''work derived from this site.'''.format(uri_txt)
    return Response(
        txt,
        mimetype='text/plain'
    )

routes/functions.py
import os
from os.path import dirname, abspath, join


def _get_posts():
    parent_dir = dirname(dirname(abspath(__file__)))
    postfiles = os.listdir(join(parent_dir, 'posts'))
    posts = []
    for pf in postfiles:
        posts.append(
            {
                'link': pf[:-3],
                'title': pf[10:-3].replace('-', ' '),
                'date': pf[:10]
            }
        )

    return posts

routes/pages.py
from flask import Blueprint, render_template, Markup
from flask_mobility.decorators import mobile_template
from os.path import dirname, abspath, join
from routes.functions import _get_posts
import markdown
pages = Blueprint('pages', __name__)


@pages.route('/')
@mobile_template('{mobile/}page.html')
def home(template):
    posts = _get_posts()
    md = open(join(dirname(dirname(abspath(__file__))), 'pages', 'home.md')).read()
    content = Markup(markdown.markdown(md))
    return render_template(template, **locals())


@pages.route('/page/<page>')
def page(page):
    posts = _get_posts()
    md = open(join(dirname(dirname(abspath(__file__))), 'pages', page + '.md')).read()
    content = Markup(markdown.markdown(md))
    return render_template('page.html', **locals())

routes/posts.py
from flask import Blueprint, render_template, Markup
from os.path import dirname, abspath, join
import markdown
from routes.functions import _get_posts
posts = Blueprint('posts', __name__)


@posts.route('/post/')
def postss():
    posts = _get_posts()
    return render_template('posts.html', posts=posts)


@posts.route('/post/<string:filename>')
def post(filename):
    posts = _get_posts()
    md = open(join(dirname(dirname(abspath(__file__))), 'posts', '{}.md'.format(filename))).read()
    content = Markup(markdown.markdown(md, extensions=['codehilite', 'fenced_code']))
    post_title = filename[10:].replace('-', ' ')
    return render_template('post.html', **locals())

templates/mobile/page.html
{% include 'page_header.html' %}

<h2>Mobile Home</h2>
<p>More to come...</p>

{% include 'page_footer.html' %}

templates/nav.html
<a href="{{ url_for('pages.home') }}">Home</a>
<a href="{{ url_for('pages.page', page='about') }}">About</a>
<a href="{{ url_for('pages.page', page='contact') }}">Contact</a>
<a href="{{ url_for('pages.page', page='tools') }}">Demo Tools</a>
<a href="{{ url_for('posts.postss') }}">Posts</a>

templates/page.html
{% include 'page_header.html' %}

<h2>Home</h2>
<p>More to come...</p>

{% include 'page_footer.html' %}

templates/page_footer.html
    </article>
    <nav style="float: right; width: 18%; margin-left:2%;">
        {% if posts != '' %}
        <h3>Posts</h3>
        <ul id="postlinks">
            {%  for post in posts %}
                <li><a href="{{ url_for('posts.post', filename=post['link']) }}">{{ post['title'] }}</a><br /><span style="font-size:smaller;">{{ post['date'] }}</span></li>
            {%  endfor %}
        </ul>
        {% endif %}
    </nav>

    <footer>
        {% include 'nav.html' %}
    </footer>
    </div><!-- #conteiner -->
</body>
</html>

templates/page_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProvBlog</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/provblog.css') }}">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Libre+Baskerville">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Asap">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/default.css') }}">
    <script src="{{ url_for('static', filename='js/highlight.pack.js') }}"></script>
    <script>
        hljs.initHighlightingOnLoad();
    </script>
</head>
<body>
    <div id="container">
        <header>
            <div id="title">PROVBLOG</div>
            <div id="links">{% include 'nav.html' %}</div>
            <div style="clear:both;"></div>
        </header>
        <article id="main">

templates/page_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/post.html
{% include 'page_header.html' %}

<h2>{{ post_title }}</h2>
{{ content|safe }}

{% include 'page_footer.html' %}

templates/post_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/post_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/posts.html
{% include 'page_header.html' %}

<h2>Posts</h2>
<ul>
{%  for post in posts %}
    <li><span style="font-size:smaller;">{{ post['date'] }}</span> <a href="{{ url_for('posts.post', filename=post['link']) }}">{{ post['title'] }}</a></li>
{%  endfor %}
</ul>

{%  set posts = '' %}
{% include 'page_footer.html' %}

templates/tools.html
{% include 'page_header.html' %}

<h2 style="font-family: Consolas, serif;">API</h2>
<p style="font-family: Consolas, serif;">More to come...</p>

{% include 'page_footer.html' %}